### ISSUE TITLE
Segmentation fault when running STEME on Mac OS X 10.11.6

### ISSUE THREAD

**Issue by themantalope** [JohnReid/STEME#1] opened 2016-08-17 20:35 UTC
When trying to run steme on a test file after compiling and installing on Mac OS X 10.11.6, I am getting this segmentation error:

``` bash
$ steme test_file.fasta
2016-08-17 15:33:45,606:INFO: Python: 2.7.10 (default, Oct 23 2015, 19:19:21)
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)]
2016-08-17 15:33:45,607:INFO: Command line: /Users/<user>/.ENV/bin/steme test_file.fasta
/Users/<user>/.ENV/lib/python2.7/site-packages/cookbook/script_basics.py:114: UserWarning: Do not know which dlopen flags to set.
  warnings.warn('Do not know which dlopen flags to set.')
2016-08-17 15:33:45,733:INFO: Loaded standard version of STEME C++-python interface: max seqs=4294967296; max seq length=4294967296; max total length=4294967296
2016-08-17 15:33:45,736:INFO: Loaded STEME C++-python interface from stempy._release_build
/Users/<user>/.ENV/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
2016-08-17 15:33:46,201:INFO: Options:
2016-08-17 15:33:46,202:INFO:
2016-08-17 15:33:46,202:INFO: Multiple motifs:
2016-08-17 15:33:46,202:INFO:                       num_motifs: 1                                * Number of motifs to look for.
2016-08-17 15:33:46,202:INFO:           prediction_Z_threshold: 0.3                              * The threshold on Z used to erase instances of motifs. The lower this is, the more instances will be erased.
2016-08-17 15:33:46,202:INFO:
2016-08-17 15:33:46,202:INFO: Output:
2016-08-17 15:33:46,202:INFO:                       output_dir: output                           * Output directory.
2016-08-17 15:33:46,202:INFO:                 meme_like_output: meme.txt                         * Produce MEME-like output so that it can be parsed by downstream tools.
2016-08-17 15:33:46,202:INFO:                      html_output: STEME.html                       * Produce HTML output.
2016-08-17 15:33:46,202:INFO:                      print_sites: False                            * Write a file containing the sites that were used to make the motif.
2016-08-17 15:33:46,202:INFO:                 dont_write_logos: False                            * Don't write logos for motifs.
2016-08-17 15:33:46,202:INFO:                   write_em_logos: False                            * Write logos for motifs during EM algorithm.
2016-08-17 15:33:46,202:INFO:                   write_em_stats: False                            * Write statistics for EM algorithm.
2016-08-17 15:33:46,202:INFO:                           tomtom: []                               * Run TOMTOM tool from the the MEME suite on the motifs using the specified motif databases.
2016-08-17 15:33:46,202:INFO:                max_seqs_to_write: 1000                             * Maximum number of sequences to write information about in output.
2016-08-17 15:33:46,202:INFO:               max_sites_to_write: 1000                             * Maximum number of sites to write information about in output.
2016-08-17 15:33:46,203:INFO:                       motif_name: STEME-                           * Name for output motifs.
2016-08-17 15:33:46,203:INFO:
2016-08-17 15:33:46,203:INFO: Background model:
2016-08-17 15:33:46,203:INFO:                   bg_model_order: 2                                * Order of the background Markov model.
2016-08-17 15:33:46,203:INFO:                    bg_fasta_file: None                             * If specified, STEME builds its background model from the sequences in this file rather than from the input sequences.
2016-08-17 15:33:46,203:INFO:                  back_dist_prior: 1.0                              * Pseudo-counts for Markov background model.
2016-08-17 15:33:46,203:INFO:
2016-08-17 15:33:46,203:INFO: Start finding:
2016-08-17 15:33:46,203:INFO:           max_start_finding_time: 0.0                              * How many seconds to dedicate to finding starts for each motif. If not given, STEME will look at each possible start (can be slow).
2016-08-17 15:33:46,203:INFO:                    min_num_sites: None                             * Minimum number of sites. Defaults to # sequences / 10.
2016-08-17 15:33:46,203:INFO:                    max_num_sites: None                             * Maximum number of sites. Defaults to 50% more than # sequences.
2016-08-17 15:33:46,203:INFO:                            width: []                               * If specified, search for motifs of this width (can specify more than one).
2016-08-17 15:33:46,203:INFO:                            min_w: 6                                * Minimum width of motif to find.
2016-08-17 15:33:46,203:INFO:                            max_w: 14                               * Maximum width of motif to find.
2016-08-17 15:33:46,203:INFO:                 starts_per_motif: 4                                * Number of starts to find per motif.
2016-08-17 15:33:46,203:INFO:                         use_seed: None                             * If specified, only use this seed as a start.
2016-08-17 15:33:46,203:INFO:        starts_seed_pseudo_counts: 0.5                              * Pseudo counts with which to smooth possible starting seeds.
2016-08-17 15:33:46,203:INFO:                  starts_speed_up: 0                                * Speed up the start finding by ignoring so many potential starting points.
2016-08-17 15:33:46,204:INFO:          candidate_starts_factor: 1.41421356237                    * The factor for the geometric progression that determines which numbers of sites to try when start finding.
2016-08-17 15:33:46,204:INFO:
2016-08-17 15:33:46,204:INFO: EM:
2016-08-17 15:33:46,204:INFO:                        max_iters: 1000                             * Maximum number of iterations for EM algorithm.
2016-08-17 15:33:46,204:INFO:                  dont_discretize: False                            * Don't run discretisation after EM.
2016-08-17 15:33:46,204:INFO:             convergence_distance: 1e-05                            * Threshold between successive iterations at which to stop EM.
2016-08-17 15:33:46,204:INFO:                          wnsites: 0.8                              * Weight on number of sites. Used when updating lambda in EM algorithm.
2016-08-17 15:33:46,204:INFO:            em_seed_pseudo_counts: 0.01                             * Pseudo counts for motif model in EM algorithm.
2016-08-17 15:33:46,204:INFO:                          epsilon: 0.4                              * Allowed error in motif probabilities for EM algorithm.
2016-08-17 15:33:46,204:INFO:
2016-08-17 15:33:46,204:INFO: Internal:
2016-08-17 15:33:46,204:INFO:                      cache_index: None                             * Save the index to disk so it does not need to be rebuilt next time.
2016-08-17 15:33:46,204:INFO:        pvalue_table_lattice_size: 0.0                              * Size of the lattice used when calculating p-values. Default is 2 * max sites.
2016-08-17 15:33:46,204:INFO:                          lambda_: 0.0                              * Likelihood of a binding site in the model. Set to reasonable value by default.
2016-08-17 15:33:46,204:INFO:                    alphabet_size: 4                                * Number of characters in the alphabet.
2016-08-17 15:33:46,204:INFO:                         write_IC:                                  * Write the starts' IC values to the given file.
2016-08-17 15:33:46,204:INFO:                   google_profile: False                            * Profile with the google profiler.
2016-08-17 15:33:46,204:INFO:              store_start_results: False                            * Retain the start results (used for testing).
2016-08-17 15:33:46,204:INFO:
2016-08-17 15:33:46,205:INFO: Running STEME 1.9.1 $Revision: 3956 $
2016-08-17 15:33:46,205:INFO: Looking for cached index information: test_file.fasta.info
2016-08-17 15:33:46,205:INFO: Could not load cached index, reading FASTA directly
2016-08-17 15:33:46,206:INFO: Read 40020 bases from 20 sequences in test_file.fasta
2016-08-17 15:33:46,206:INFO: Initialising index
2016-08-17 15:33:46,206:INFO: max_W=14
2016-08-17 15:33:46,223:INFO: Using a Markov model of order 2
2016-08-17 15:33:46,223:INFO: Maximum number of sites not explicitly set. Was set to 30.
2016-08-17 15:33:46,223:INFO: Minimum number of sites not explicitly set. Was set to 2.
2016-08-17 15:33:46,224:INFO: Timer: Took 0.018735 seconds to load sequences
2016-08-17 15:33:46,224:INFO: Building background Markov model from input sequences
2016-08-17 15:33:46,224:INFO: Calculating likelihoods of 40020 bases.
2016-08-17 15:33:46,224:INFO: Timer: Took 0.000665 seconds to initialise background model
2016-08-17 15:33:46,225:INFO: Timer: Took 0.000152 seconds to initialise p-value tables for numbers of sites from 2 to 30
Segmentation fault: 11


edit: removed name for privacy
```

**Comment by JohnReid** [comment] 2016-08-17 20:38
Thanks for the bug report. Can you attach the FASTA file that is causing the problem? Thanks.

**Comment by themantalope** [comment] 2016-08-17 20:43
Here is the file.
[test_file.fasta.txt](https://github.com/JohnReid/STEME/files/423586/test_file.fasta.txt)

**Comment by JohnReid** [comment] 2016-08-17 21:01
I can't reproduce this on my system. I'm guessing it has to be an issue with how STEME was compiled. If you could get a stack trace that might help.

**Comment by themantalope** [comment] 2016-08-17 21:21
Here is the crash log.
[python_2016-08-17-160856_dhcp-129-105-163-165.crash.txt](https://github.com/JohnReid/STEME/files/423641/python_2016-08-17-160856_dhcp-129-105-163-165.crash.txt)

**Comment by JohnReid** [comment] 2016-08-17 21:29
That's the first time I've seen a MacOS crash log. Nothing stands out in it. It is pretty late here so I'm going to see if I can make more sense of it in the morning.

**Comment by themantalope** [comment] 2016-08-17 21:34
Thanks for taking a look!

**Comment by JohnReid** [comment] 2016-08-18 08:42
I don't think there's enough information in the crash log to tell what went wrong. If it works on my machine but not on yours, it is almost definitely some sort of compilation issue although tracking down what is not easy. Could you describe how you built STEME?

**Comment by themantalope** [comment] 2016-08-18 14:23
1) Downloaded the project from Github
2) Installed boost, boost-python and fftw via homebrew using the `--cc=gcc-4.9` and `--build-from-source` options. Using the homebrew "bottled" versions of the software led to failure during compilation.
3) I separately downloaded the SeqAn library v1.4.0.
4) I configured the siteconf.py file during configuration, providing paths to the boost/lib, boost/include and seqan library directories. 
5) I then compiled STEME using gcc-4.9. The project compiled without any errors (although many warnings came up during compilation). Running `steme --help` did not produce any errors, but the segmentation fault came in when trying to analyze a file.

**Comment by JohnReid** [comment] 2016-08-18 14:32
Thanks for the info. Is there any reason you didn't use SeqAn 1.4.2? I know STEME doesn't work with version 2 and above. That could be a long shot but it could help. I'm not sure I've tried building STEME with gcc-4.9. I'm guessing the warnings are to do with gcc catching up with the C++ standard. Could you upload the warnings here just so I can check?

**Comment by themantalope** [comment] 2016-08-18 16:23
Hi John,

I'll attach the most recent build log here. Let me know if there is something else I should do to help. In addition, after this most recent build (STEME v 1.9.3, compiled on gcc-4.2) I am now getting a different error:

``` python
ERROR: File "/Users/<user>/.ENV/lib/python2.7/site-packages/STEME-1.9.3-py2.7-macosx-10.11-intel.egg/stempy/_release_build/_index_standard_wrapper.py", line 8, in <module>
    from ._index import *
2016-08-18 10:43:39,881:ERROR: TypeError: No registered converter was able to produce a C++ rvalue of type std::string from this Python object of type str
```

Build log is here:
[buildlog.txt](https://github.com/JohnReid/STEME/files/425397/buildlog.txt)

edit: edited for formatting, clarity

**Comment by JohnReid** [comment] 2016-08-18 16:41
That is a lot of warnings but they all look OK to me. FWIW I recommend you try SeqAn 1.4.2 as I vaguely remember some problems with old versions of SeqAn. And my system is using boost 1.58 although I think changing that is less likely to help. I also recommend compiling all the libraries you are using with the same version of gcc and this should be the most recent version you have. If that doesn't work, I'm not sure what to suggest next.

**Comment by themantalope** [comment] 2016-08-18 16:45
I've also tried to compile the libraries and STEME using different compilers as well, everything available on mac from gcc-4.2 to gcc-6, and even clang. In most cases, STEME would compile but would encounter some kind of error at run time. I have also tried to compile with SeqAn 1.4.2 but it hasn't made a difference, I'm afraid.

**Comment by JohnReid** [comment] 2016-08-18 16:52
OK that's a real shame. I don't think there's much I can do without access to a Mac. Thanks for sticking with it for so long and I'm sorry we didn't get it working. I'll close this issue unless there's anything else you want to add or try.

**Comment by themantalope** [comment] 2016-08-18 17:00
Just recompiled everything using gcc-5, alas I'm still getting some kind of exception (which I'm guessing is coming from boost):

``` python
ERROR: File "/Users/antalek/.ENV/lib/python2.7/site-packages/STEME-1.9.3-py2.7-macosx-10.11-intel.egg/stempy/_meme_like_output.py", line 81, in <genexpr>
    '\n'.join("%-24s 1.0000 %6d" % (_id, algorithm.input_sequences.seqs.string_length(i))
2016-08-18 11:57:30,199:ERROR: RuntimeError: unidentifiable C++ exception
```

I guess for now I'll still use the online version. I was interested in compiling and running on my local machine for the convenience of the downstream analyses built into the package. Is there any way to use those tools on the web server?

**Comment by JohnReid** [comment] 2016-08-18 17:13
I'm not sure where that error is coming from.

I'm afraid the web-server just has the motif finding functionality in it.

I did think of one other thing you might try. Have you considered using a virtual machine? I have used them successfully in the past. It might be worth checking if you can run Ubuntu in a virtual machine on your Mac.

**Comment by themantalope** [comment] 2016-08-18 17:27
It is possible to run a Ubuntu on Mac as a virtual machine. I can give that a shot. Could you kindly let me know exactly what your set up is on your ubuntu machine and the necessary steps to compile STEME on ubuntu?

**Comment by JohnReid** [comment] 2016-08-18 17:38
I've had it compile on all sorts of version of Ubuntu. At the moment I'm using 16.04. That's the most recent and probably the best choice. The installation instructions are here:
https://pythonhosted.org/STEME/getting_started.html
Let me know how you go.

**Closed as completed** 2017-07-11 07:29 UTC
